name: Publish
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - id: install-secret-key
        name: Install GPG secret key
        run: |
          export GPG_TTY=$(tty)
          echo "Install gpg secret key"
          cat <(echo -e "${{ secrets.GPG_SECRET_KEY }}") | gpg --batch --import
          echo "Verify gpg secret key"
          gpg --list-secret-keys --keyid-format LONG

      - name: Publish library
        run: ./gradlew clean build publishToSonatype -Psigning.gnupg.keyName=568EC4DD -Psigning.gnupg.passphrase=${{ secrets.GPG_SECRET_KEY_PASSWORD }}
        env:
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_USERNAME }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_PASSWORD }}
